### ISSUE TITLE
HTTPS using Hyper ?

### ISSUE THREAD

**Issue by Paulo-21** [Paulo-21/RustWeb#1]
Je pense qu'il faudrait utilisé Rustls

**Comment by Paulo-21** [comment]
Did you investigate ? @Benskalz

**Comment by Benskalz** [comment]
i don't know rust, leave me alone

**Comment by Paulo-21** [comment]
Je pense qu'il serait préférable d'utilisé hyper ou wrap derrière un proxy nginx pour commencer
Je ne pense pas que les librairies et Framework web soit assez mature pour être utilisé en première ligne.

**Comment by Benskalz** [comment]
I think node js + nginx reverse proxy is good and a little lestencrypt ssl is perfect

**Comment by Benskalz** [comment]
ah my bad you want to use rust so yes Hyper is an HTTP library for Rust it should be good

**Comment by Benskalz** [comment]
rustls is A modern TLS library in Rust so it's enven better than hyper IMO because you have TLS

**Comment by Benskalz** [comment]
did you already tested rustls ? @Paulo-21 
I never used it so idk if it's production compatible

**Comment by Paulo-21** [comment]
Yes a tested a bit but it's too hard to rebuild a server from scratch

**Comment by Benskalz** [comment]
just checked actix.rs, seems good to me, I like routing syntax and ssl certificate should be [easy to setup ](https://github.com/actix/examples/tree/master/security/rustls/)

**Comment by Paulo-21** [comment]
#4 
I think that resolve the problem ?

**Comment by Paulo-21** [comment]
Resolved by #4
